# Generated by Django 6.0.4 on 2026-04-23 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_note', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('saved', 'Saved')], default='draft', max_length=20)),
                ('latest_disposition', models.CharField(blank=True, choices=[('Admit', 'Admit'), ('Observe', 'Observe'), ('Discharge', 'Discharge'), ('Unknown', 'Unknown')], max_length=20, null=True)),
                ('has_user_edits', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint_final', models.TextField(blank=True)),
                ('hpi_summary_final', models.TextField(blank=True)),
                ('key_findings_final', models.JSONField(blank=True, default=list)),
                ('suspected_conditions_final', models.JSONField(blank=True, default=list)),
                ('disposition_final', models.CharField(choices=[('Admit', 'Admit'), ('Observe', 'Observe'), ('Discharge', 'Discharge'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('uncertainties_final', models.JSONField(blank=True, default=list)),
                ('revised_hpi_final', models.TextField(blank=True)),
                ('edited_fields', models.JSONField(blank=True, default=list)),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edited_result', to='cases.case')),
            ],
            options={
                'verbose_name': 'Edited result',
                'verbose_name_plural': 'Edited results',
            },
        ),
        migrations.CreateModel(
            name='GeneratedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint_generated', models.TextField(blank=True)),
                ('hpi_summary_generated', models.TextField(blank=True)),
                ('key_findings_generated', models.JSONField(blank=True, default=list)),
                ('suspected_conditions_generated', models.JSONField(blank=True, default=list)),
                ('disposition_generated', models.CharField(choices=[('Admit', 'Admit'), ('Observe', 'Observe'), ('Discharge', 'Discharge'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('uncertainties_generated', models.JSONField(blank=True, default=list)),
                ('revised_hpi_generated', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_result', to='cases.case')),
            ],
            options={
                'verbose_name': 'Generated result',
                'verbose_name_plural': 'Generated results',
            },
        ),
    ]
